In [21]:
!python -m pip install requests

Requirement already satisfied: requests in .\.venv\Lib\site-packages (2.34.2)
Requirement already satisfied: charset_normalizer<4,>=2 in .\.venv\Lib\site-packages (from requests) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in .\.venv\Lib\site-packages (from requests) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in .\.venv\Lib\site-packages (from requests) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in .\.venv\Lib\site-packages (from requests) (2026.6.17)

In [22]:
import requests

url = 'https://jsonplaceholder.typicode.com/posts/1'
response = requests.get(url)

In [23]:
response

In [24]:
response.status_code

200

In [25]:
response.content

b'{\n  "userId": 1,\n  "id": 1,\n  "title": "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",\n  "body": "quia et suscipit\\nsuscipit recusandae consequuntur expedita et cum\\nreprehenderit molestiae ut ut quas totam\\nnostrum rerum est autem sunt rem eveniet architecto"\n}'

In [26]:
if response.status_code == 200:
    print('API 요청 성공')
    data = response.json() # JSON 응답을 파이썬 딕셔너리로 변환
    print(type(data))
    print('제목:', data['title'])
    print('내용:', data['body'])
else:
    print('API 요청 실패. 상태 코드:', response.status_code)

API 요청 성공
<class 'dict'>
제목: sunt aut facere repellat provident occaecati excepturi optio reprehenderit
내용: quia et suscipit
suscipit recusandae consequuntur expedita et cum
reprehenderit molestiae ut ut quas totam
nostrum rerum est autem sunt rem eveniet architecto

### BeautifulSoup 사용법

In [11]:
!python -m pip install beautifulsoup4

Collecting beautifulsoup4
  Downloading beautifulsoup4-4.15.0-py3-none-any.whl.metadata (3.8 kB)
Collecting soupsieve>=1.6.1 (from beautifulsoup4)
  Downloading soupsieve-2.8.4-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: typing-extensions>=4.0.0 in .\.venv\Lib\site-packages (from beautifulsoup4) (4.15.0)
Downloading beautifulsoup4-4.15.0-py3-none-any.whl (109 kB)
Downloading soupsieve-2.8.4-py3-none-any.whl (37 kB)
Installing collected packages: soupsieve, beautifulsoup4

   -------------------- ------------------- 1/2 [beautifulsoup4]
   -------------------- ------------------- 1/2 [beautifulsoup4]
   ---------------------------------------- 2/2 [beautifulsoup4]

Successfully installed beautifulsoup4-4.15.0 soupsieve-2.8.4

### 파이낸스 뉴스

In [27]:
import requests
from bs4 import BeautifulSoup

base_url = 'https://finance.naver.com/news/mainnews.naver'
response = requests.get(base_url)
status_code = response.status_code
if status_code == 200:
    html = response.text
    soup = BeautifulSoup(html, 'html.parser')
    articles = soup.select('.block1')

    print(status_code, len(articles))
else:
    print('요청 실패. 상태 코드:', status_code)

200 20

In [28]:
for article in articles:
    print(article)

<li class="block1">
<dl>
<dt class="thumb">
<a href="/news/news_read.naver?article_id=0004632910&amp;office_id=011&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1"><img onerror="this.src='https://ssl.pstatic.net/static/nfinance/2017/02/27/thumb_72x54.gif'" src="https://imgnews.pstatic.net/image/thumb70/011/2026/06/19/4632910.jpg"/></a>
</dt>
<dd class="articleSubject">
<a href="/news/news_read.naver?article_id=0004632910&amp;office_id=011&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1">“그때 내가 왜 그랬을까, 삼전이나 더 살걸”…삼성전자, 비트코인 시총 앞섰다</a>
</dd>
<dd class="articleSummary">
										삼성전자 시가총액이 비트코인을 2460억달러 이상 앞섰다. 코스피가 사상 처음으로 장중 9000선을 돌파하면서 반도체주가 강세를 보인 ..
										<span class="press">서울경제 </span>
<span class="bar">|</span>
<span class="wdate">2026-06-19 13:49:09</span>
</dd>
</dl>
</li>
<li class="block1">
<dl>
<dt class="thumb">
<a href="/news/news_read.naver?article_id=0004632901&amp;office_id=011&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1"><img onerror="this.src='https://ssl.pstatic.net/static/nfinance/2017/02/27/thumb_72x54.gif'" src="https://imgnews.pstatic.net/image/thumb70/011/2026/06/19/4632901.jpg"/></a>
</dt>
<dd class="articleSubject">
<a href="/news/news_read.naver?article_id=0004632901&amp;office_id=011&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1">반도체 쏠림에 ‘9000선’ 내준 코스피…코스닥은 5%대 급락[마켓시그널]</a>
</dd>
<dd class="articleSummary">
										코스피지수가 19일 장 초반 9300선을 돌파한 뒤 하락 전환했다. 미국 반도체주 강세를 타고 개장 직후 사상 최고치를 다시 썼지만 미..
										<span class="press">서울경제 </span>
<span class="bar">|</span>
<span class="wdate">2026-06-19 13:21:09</span>
</dd>
</dl>
</li>
<li class="block1">
<dl>
<dt class="thumb">
<a href="/news/news_read.naver?article_id=0005778802&amp;office_id=277&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1"><img onerror="this.src='https://ssl.pstatic.net/static/nfinance/2017/02/27/thumb_72x54.gif'" src="https://imgnews.pstatic.net/image/thumb70/277/2026/06/19/5778802.jpg"/></a>
</dt>
<dd class="articleSubject">
<a href="/news/news_read.naver?article_id=0005778802&amp;office_id=277&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1">메리츠금융 "홈플러스 투자로 1.2조 챙긴 MBK…경영 책임 다해야"</a>
</dd>
<dd class="articleSummary">
										메리츠금융그룹이 홈플러스 회생 지원과 관련한 MBK파트너스 측 입장에 대해 "대주주의 경영 실패 책임을 채권단에 전가하고 있다"며 강하..
										<span class="press">아시아경제 </span>
<span class="bar">|</span>
<span class="wdate">2026-06-19 12:35:56</span>
</dd>
</dl>
</li>
<li class="block1">
<dl>
<dt class="thumb">
<a href="/news/news_read.naver?article_id=0004632890&amp;office_id=011&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1"><img onerror="this.src='https://ssl.pstatic.net/static/nfinance/2017/02/27/thumb_72x54.gif'" src="https://imgnews.pstatic.net/image/thumb70/011/2026/06/19/4632890.jpg"/></a>
</dt>
<dd class="articleSubject">
<a href="/news/news_read.naver?article_id=0004632890&amp;office_id=011&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1">‘37만전자’ 담는 ‘상위 1%’…1만피 향해 반도체·전력기기株 베팅[주식초고수는 지금]</a>
</dd>
<dd class="articleSummary">
										미래에셋증권에서 거래하는 고수익 투자자들이 19일 가장 많이 순매수한 종목은 삼성전자(005930), HD현대일렉트릭(267260), ..
										<span class="press">서울경제 </span>
<span class="bar">|</span>
<span class="wdate">2026-06-19 11:40:06</span>
</dd>
</dl>
</li>
<li class="block1">
<dl>
<dt class="thumb">
<a href="/news/news_read.naver?article_id=0016147980&amp;office_id=001&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1"><img onerror="this.src='https://ssl.pstatic.net/static/nfinance/2017/02/27/thumb_72x54.gif'" src="https://imgnews.pstatic.net/image/thumb70/001/2026/06/19/16147980.jpg"/></a>
</dt>
<dd class="articleSubject">
<a href="/news/news_read.naver?article_id=0016147980&amp;office_id=001&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1">코스피, 2%대↑ 9,200선 등락…코스닥은 1,000선 내줘</a>
</dd>
<dd class="articleSummary">
										국내증시 시총 첫 8천조…하이닉스 시총 2천조 돌파 코스닥 또 하락해 1,000 아래로 전날 '9천피'(9,000)를 돌파했던 코스피가..
										<span class="press">연합뉴스 </span>
<span class="bar">|</span>
<span class="wdate">2026-06-19 11:38:08</span>
</dd>
</dl>
</li>
<li class="block1">
<dl>
<dt class="thumb">
<a href="/news/news_read.naver?article_id=0005374355&amp;office_id=008&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1"><img onerror="this.src='https://ssl.pstatic.net/static/nfinance/2017/02/27/thumb_72x54.gif'" src="https://imgnews.pstatic.net/image/thumb70/008/2026/06/19/5374355.jpg"/></a>
</dt>
<dd class="articleSubject">
<a href="/news/news_read.naver?article_id=0005374355&amp;office_id=008&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1">'삼전닉스 패밀리' 일제히 신고가…코스피 최고치 행진 이끈다</a>
</dd>
<dd class="articleSummary">
										코스피가 9000선을 터치한 지 하루 만에 9300선까지 돌파했다. 반도체 대장주인 삼성전자와 SK하이닉스뿐 아니라 두 회사의 지분을 ..
										<span class="press">머니투데이 </span>
<span class="bar">|</span>
<span class="wdate">2026-06-19 11:37:05</span>
</dd>
</dl>
</li>
<li class="block1">
<dl>
<dt class="thumb">
<a href="/news/news_read.naver?article_id=0002658854&amp;office_id=016&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1"><img onerror="this.src='https://ssl.pstatic.net/static/nfinance/2017/02/27/thumb_72x54.gif'" src="https://imgnews.pstatic.net/image/thumb70/016/2026/06/19/2658854.jpg"/></a>
</dt>
<dd class="articleSubject">
<a href="/news/news_read.naver?article_id=0002658854&amp;office_id=016&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1">60대이상, 2배·3배 해외 ETF 대거 편입 [머니무브 뉴웨이브][H-EXCLUSIVE]</a>
</dd>
<dd class="articleSummary">
										코스피 지수가 9000선을 넘어선 강세장 속에서 60대 이상 투자자도 대거 2배·3배 레버리지 상장지수펀드(ETF) 상품에 투자하고 있..
										<span class="press">헤럴드경제 </span>
<span class="bar">|</span>
<span class="wdate">2026-06-19 11:19:15</span>
</dd>
</dl>
</li>
<li class="block1">
<dl>
<dt class="thumb">
<a href="/news/news_read.naver?article_id=0002658850&amp;office_id=016&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1"><img onerror="this.src='https://ssl.pstatic.net/static/nfinance/2017/02/27/thumb_72x54.gif'" src="https://imgnews.pstatic.net/image/thumb70/016/2026/06/19/2658850.jpg"/></a>
</dt>
<dd class="articleSubject">
<a href="/news/news_read.naver?article_id=0002658850&amp;office_id=016&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1">“전세금 빼서 주식에”…고위험 레버리지도 거침없는 6070 [머니무브 뉴웨이브]</a>
</dd>
<dd class="articleSummary">
										“전세 대신 월세를 살기로 했어요. 그 돈은 주식에 전부 넣었습니다.” 6월 초 서울 한 증권사 투자센터. 점심시간이 막 지난 시간이지..
										<span class="press">헤럴드경제 </span>
<span class="bar">|</span>
<span class="wdate">2026-06-19 11:18:10</span>
</dd>
</dl>
</li>
<li class="block1">
<dl>
<dt class="thumb">
<a href="/news/news_read.naver?article_id=0002658845&amp;office_id=016&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1"><img onerror="this.src='https://ssl.pstatic.net/static/nfinance/2017/02/27/thumb_72x54.gif'" src="https://imgnews.pstatic.net/image/thumb70/016/2026/06/19/2658845.jpg"/></a>
</dt>
<dd class="articleSubject">
<a href="/news/news_read.naver?article_id=0002658845&amp;office_id=016&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1">삼성·SK그룹주 첫 5000조 돌파…코스피 70% 차지</a>
</dd>
<dd class="articleSummary">
										코스피가 사상 처음으로 9000선을 돌파한 데에는 삼성전자와 SK하이닉스의 급등이 주효했다. 이에 힘입어 삼성그룹과 SK그룹 상장 계열..
										<span class="press">헤럴드경제 </span>
<span class="bar">|</span>
<span class="wdate">2026-06-19 11:17:07</span>
</dd>
</dl>
</li>
<li class="block1">
<dl>
<dt class="thumb">
<a href="/news/news_read.naver?article_id=0002658844&amp;office_id=016&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1"><img onerror="this.src='https://ssl.pstatic.net/static/nfinance/2017/02/27/thumb_72x54.gif'" src="https://imgnews.pstatic.net/image/thumb70/016/2026/06/19/2658844.jpg"/></a>
</dt>
<dd class="articleSubject">
<a href="/news/news_read.naver?article_id=0002658844&amp;office_id=016&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1">만스피 시대 목전…새로운 ‘M·A·P’ 열렸다</a>
</dd>
<dd class="articleSummary">
										코스피가 전인미답의 9000선 고지를 밟았다. 코스피 상장 기업들의 합산 시가총액은 사상 처음으로 7400조원을 돌파했다. 지난해 말과..
										<span class="press">헤럴드경제 </span>
<span class="bar">|</span>
<span class="wdate">2026-06-19 11:16:11</span>
</dd>
</dl>
</li>
<li class="block1">
<dl>
<dt class="thumb">
<a href="/news/news_read.naver?article_id=0002658812&amp;office_id=016&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1"><img onerror="this.src='https://ssl.pstatic.net/static/nfinance/2017/02/27/thumb_72x54.gif'" src="https://imgnews.pstatic.net/image/thumb70/016/2026/06/19/2658812.jpg"/></a>
</dt>
<dd class="articleSubject">
<a href="/news/news_read.naver?article_id=0002658812&amp;office_id=016&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1">SK하이닉스 이러다 삼성전자 추월?…7% 급등에 ‘280만닉스’, 시총 2000조 돌파 [종목 Pick]</a>
</dd>
<dd class="articleSummary">
										SK하이닉스가 19일 장 초반 7% 넘게 급등하며 사상 처음으로 ‘280만 닉스’에 도달했다. SK하이닉스의 시가총액은 2000조원을 ..
										<span class="press">헤럴드경제 </span>
<span class="bar">|</span>
<span class="wdate">2026-06-19 11:01:10</span>
</dd>
</dl>
</li>
<li class="block1">
<dl>
<dt class="thumb">
<a href="/news/news_read.naver?article_id=0005537170&amp;office_id=014&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1"><img onerror="this.src='https://ssl.pstatic.net/static/nfinance/2017/02/27/thumb_72x54.gif'" src="https://imgnews.pstatic.net/image/thumb70/014/2026/06/19/5537170.jpg"/></a>
</dt>
<dd class="articleSubject">
<a href="/news/news_read.naver?article_id=0005537170&amp;office_id=014&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1">"삼성전기 300만원 간다...MLCC·기판, 없어서 못 팔아"…KT&amp;G, 해외 매출 증가에 주주 환원 확대까지 '재평가' [株토피아]</a>
</dd>
<dd class="articleSummary">
										6월 19일 오전, 주요 증권사 리포트를 정리해드립니다. 삼성전기는 인공지능(AI) 서버용 적층세라믹콘덴서(MLCC)와 패키징 기판 모..
										<span class="press">파이낸셜뉴스 </span>
<span class="bar">|</span>
<span class="wdate">2026-06-19 11:00:11</span>
</dd>
</dl>
</li>
<li class="block1">
<dl>
<dt class="thumb">
<a href="/news/news_read.naver?article_id=0004632866&amp;office_id=011&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1"><img onerror="this.src='https://ssl.pstatic.net/static/nfinance/2017/02/27/thumb_72x54.gif'" src="https://imgnews.pstatic.net/image/thumb70/011/2026/06/19/4632866.jpg"/></a>
</dt>
<dd class="articleSubject">
<a href="/news/news_read.naver?article_id=0004632866&amp;office_id=011&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1">“너도 주식한다고 했지? 꽤 벌었겠네”…이 말에 코스닥 개미들은 ‘눈물’</a>
</dd>
<dd class="articleSummary">
										코스피가 사상 처음으로 9000선을 넘어섰지만 코스닥은 철저히 소외됐다. 연초 이후 두 지수의 수익률 격차는 100%포인트를 웃돌고 있..
										<span class="press">서울경제 </span>
<span class="bar">|</span>
<span class="wdate">2026-06-19 10:43:08</span>
</dd>
</dl>
</li>
<li class="block1">
<dl>
<dt class="thumb">
<a href="/news/news_read.naver?article_id=0004632860&amp;office_id=011&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1"><img onerror="this.src='https://ssl.pstatic.net/static/nfinance/2017/02/27/thumb_72x54.gif'" src="https://imgnews.pstatic.net/image/thumb70/011/2026/06/19/4632860.jpg"/></a>
</dt>
<dd class="articleSubject">
<a href="/news/news_read.naver?article_id=0004632860&amp;office_id=011&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1">스페이스X에 꽂힌 서학개미…사흘 만에 2.7조 쓸어담았다[코주부]</a>
</dd>
<dd class="articleSummary">
										미국 증시에 투자하는 국내 개인투자자들이 우주항공 기업 스페이스X로 빠르게 몰리고 있다. 상장 직후 주가가 급등하자 이른바 ‘서학개미’..
										<span class="press">서울경제 </span>
<span class="bar">|</span>
<span class="wdate">2026-06-19 10:36:14</span>
</dd>
</dl>
</li>
<li class="block1">
<dl>
<dt class="thumb">
<a href="/news/news_read.naver?article_id=0005537151&amp;office_id=014&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1"><img onerror="this.src='https://ssl.pstatic.net/static/nfinance/2017/02/27/thumb_72x54.gif'" src="https://imgnews.pstatic.net/image/thumb70/014/2026/06/19/5537151.jpg"/></a>
</dt>
<dd class="articleSubject">
<a href="/news/news_read.naver?article_id=0005537151&amp;office_id=014&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1">'삼전·닉스' 믿은 개인들 웃었다…8000→9000 구간 수익률 압승</a>
</dd>
<dd class="articleSummary">
										코스피가 종가 기준 8000선을 돌파한 이후 9000선을 넘어서는 과정에서 가장 큰 승자는 삼성전자와 SK하이닉스를 선택한 개인 투자자..
										<span class="press">파이낸셜뉴스 </span>
<span class="bar">|</span>
<span class="wdate">2026-06-19 10:15:11</span>
</dd>
</dl>
</li>
<li class="block1">
<dl>
<dt class="thumb">
<a href="/news/news_read.naver?article_id=0001255937&amp;office_id=215&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1"><img onerror="this.src='https://ssl.pstatic.net/static/nfinance/2017/02/27/thumb_72x54.gif'" src="https://imgnews.pstatic.net/image/thumb70/215/2026/06/19/1255937.jpg"/></a>
</dt>
<dd class="articleSubject">
<a href="/news/news_read.naver?article_id=0001255937&amp;office_id=215&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1">형님 뛰자 동반 '뜀박질'…목표주가 38만→62만원 "우리는 더 오른다"</a>
</dd>
<dd class="articleSummary">
										코스피가 19일 장 초반 9,300선을 돌파하며 다시 사상 최고치를 경신했다. 미국발 반도체 호재에 힘입어 삼성전자와 SK하이닉스가 나..
										<span class="press">한국경제TV </span>
<span class="bar">|</span>
<span class="wdate">2026-06-19 10:12:38</span>
</dd>
</dl>
</li>
<li class="block1">
<dl>
<dt class="thumb">
<a href="/news/news_read.naver?article_id=0004632843&amp;office_id=011&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1"><img onerror="this.src='https://ssl.pstatic.net/static/nfinance/2017/02/27/thumb_72x54.gif'" src="https://imgnews.pstatic.net/image/thumb70/011/2026/06/19/4632843.jpg"/></a>
</dt>
<dd class="articleSubject">
<a href="/news/news_read.naver?article_id=0004632843&amp;office_id=011&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1">SK스퀘어, 189만 원 ‘터치’…목표가 뚫고 9%대 ‘급등’[이런국장 저런주식]</a>
</dd>
<dd class="articleSummary">
										SK스퀘어(402340)가 19일 장 초반 9% 넘게 급등하며 장중 신고가를 다시 썼다. 핵심 자회사인 SK하이닉스(000660) 주가..
										<span class="press">서울경제 </span>
<span class="bar">|</span>
<span class="wdate">2026-06-19 10:07:15</span>
</dd>
</dl>
</li>
<li class="block1">
<dl>
<dt class="thumb">
<a href="/news/news_read.naver?article_id=0004632840&amp;office_id=011&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1"><img onerror="this.src='https://ssl.pstatic.net/static/nfinance/2017/02/27/thumb_72x54.gif'" src="https://imgnews.pstatic.net/image/thumb70/011/2026/06/19/4632840.jpg"/></a>
</dt>
<dd class="articleSubject">
<a href="/news/news_read.naver?article_id=0004632840&amp;office_id=011&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1">매파 연준 쇼크…환율 1527원 다시 뚫었다</a>
</dd>
<dd class="articleSummary">
										▲ AI 프리즘* 맞춤형 경제 브리핑 * 편집자 주: ‘AI PRISM’(Personalized Report &amp; Insight Summ..
										<span class="press">서울경제 </span>
<span class="bar">|</span>
<span class="wdate">2026-06-19 10:06:11</span>
</dd>
</dl>
</li>
<li class="block1">
<dl>
<dt class="thumb">
<a href="/news/news_read.naver?article_id=0006309682&amp;office_id=018&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1"><img onerror="this.src='https://ssl.pstatic.net/static/nfinance/2017/02/27/thumb_72x54.gif'" src="https://imgnews.pstatic.net/image/thumb70/018/2026/06/19/6309682.jpg"/></a>
</dt>
<dd class="articleSubject">
<a href="/news/news_read.naver?article_id=0006309682&amp;office_id=018&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1">FTSE 리밸런싱에 쏠린 눈…“SK하이닉스 장마감 매도 유의”</a>
</dd>
<dd class="articleSummary">
										FTSE Korea 리밸런싱을 앞두고 삼성전자(005930)와 SK하이닉스(000660)의 비중 조정에 따른 장마감 수급 변동성에 유의..
										<span class="press">이데일리 </span>
<span class="bar">|</span>
<span class="wdate">2026-06-19 10:04:09</span>
</dd>
</dl>
</li>
<li class="block1">
<dl>
<dt class="thumb">
<a href="/news/news_read.naver?article_id=0004632828&amp;office_id=011&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1"><img onerror="this.src='https://ssl.pstatic.net/static/nfinance/2017/02/27/thumb_72x54.gif'" src="https://imgnews.pstatic.net/image/thumb70/011/2026/06/19/4632828.jpg"/></a>
</dt>
<dd class="articleSubject">
<a href="/news/news_read.naver?article_id=0004632828&amp;office_id=011&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1">“전력기기株 다시 전류 통했나”…LS일렉 12%·효성重 8% 급등[이런국장 저런주식]</a>
</dd>
<dd class="articleSummary">
										전력기기주가 19일 장중 일제히 강세를 보이고 있다. 인공지능(AI) 데이터센터 확대에 따른 전력망 투자 기대가 이어지는 가운데 최근 ..
										<span class="press">서울경제 </span>
<span class="bar">|</span>
<span class="wdate">2026-06-19 09:50:07</span>
</dd>
</dl>
</li>

In [ ]:
article_list = []

for article in articles:
    title = article.select_one('.articleSubject > a').text.strip() # 앵커 태그
    link = article.select_one('.articleSubject > a').attrs['href']
    content = article.select_one('.articleSummary').contents[0].strip()
    press = article.select_one('.press').text.strip()
    date = article.select_one('.wdate').text.strip()
    
    article_list.append([title, link, content, press, date])

print(len(article_list))

20

### 네이버 파이낸스 뉴스 URL
- https://finance.naver.com/news/mainnews.naver
- https://finance.naver.com/news/mainnews.naver?&page=2
- https://finance.naver.com/news/mainnews.naver?&page=3

In [34]:
import time

base_url = 'https://finance.naver.com/news/mainnews.naver'
article_list = []

for page_num in range(1, 5):
    news_url = f'{base_url}?&page={page_num}'
    response = requests.get(news_url)
    status_code = response.status_code
    if status_code == 200:
        html = response.text
        soup = BeautifulSoup(html, 'html.parser')
        articles = soup.select('.block1')

        for article in articles:
            title = article.select_one('.articleSubject > a').text.strip()
            link = article.select_one('.articleSubject > a').attrs['href']
            content = article.select_one('.articleSummary').contents[0].strip()
            press = article.select_one('.press').text.strip()
            date = article.select_one('.wdate').text.strip()
            
            article_list.append([title, link, content, press, date])

        print(f'{page_num}번째 페이지 - 기사 개수 {len(articles)}')
    else:
        print('요청 실패. 상태 코드:', status_code)
    
    time.sleep(5)

print(f'전체 기사 개수 {len(article_list)}')

1번째 페이지 - 기사 개수 20
2번째 페이지 - 기사 개수 20
3번째 페이지 - 기사 개수 20
4번째 페이지 - 기사 개수 17
전체 기사 개수 77

In [31]:
print(article_list[19])

['“전력기기株 다시 전류 통했나”…LS일렉 12%·효성重 8% 급등[이런국장 저런주식]', '/news/news_read.naver?article_id=0004632828&office_id=011&mode=mainnews&type=&date=2026-06-19&page=1', '전력기기주가 19일 장중 일제히 강세를 보이고 있다. 인공지능(AI) 데이터센터 확대에 따른 전력망 투자 기대가 이어지는 가운데 최근 ..', '서울경제', '2026-06-19 09:50:07']

In [32]:
print(article_list[20])

['무섭게 오르는 코스피…구천피 넘자마자 9300 돌파 ‘또 최고치’ [투자360]', '/news/news_read.naver?article_id=0002658737&office_id=016&mode=mainnews&type=&date=2026-06-19&page=2', '전날 사상 처음으로 9000선 고지를 밟은 코스피가 19일 상승세를 이어가며 장중 최고치를 경신, 9300선마저 돌파했다. ‘팔천피’(..', '헤럴드경제', '2026-06-19 09:40:07']

In [33]:
print(article_list[-1])

['외인 떠나도 \'9000피\'..."우리가 끌어올릴게" 개미 \'73조\' 실탄 쐈다', '/news/news_read.naver?article_id=0005374156&office_id=008&mode=mainnews&type=&date=2026-06-19&page=4', "'코스피 9000' 시대를 연 주인공은 개인투자자다. 개인은 올해 코스피 시장에서 73조원어치를 사들이며 외국인의 순매도 공세를 막아냈..", '머니투데이', '2026-06-19 04:14:00']

In [17]:
article_list = []

for article in articles:
    title = article.select_one('.articleSubject > a').text
    print(title)
    break

‘37만전자’ 담는 ‘상위 1%’…1만피 향해 반도체·전력기기株 베팅[주식초고수는 지금]

In [18]:
article_list = []

for article in articles:
    title = article.select_one('.articleSubject > a').text.strip()
    link = article.select_one('.articleSubject > a').attrs['href']
    content = article.select_one('.articleSummary').contents[0].strip()
    press = article.select_one('.press').text.strip()
    date = article.select_one('.wdate').text.strip()
    
    article_list.append([title, link, content, press, date])

print(len(article_list))

20

In [19]:
for article in articles:
    print(article)

<li class="block1">
<dl>
<dt class="thumb">
<a href="/news/news_read.naver?article_id=0004632890&amp;office_id=011&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1"><img onerror="this.src='https://ssl.pstatic.net/static/nfinance/2017/02/27/thumb_72x54.gif'" src="https://imgnews.pstatic.net/image/thumb70/011/2026/06/19/4632890.jpg"/></a>
</dt>
<dd class="articleSubject">
<a href="/news/news_read.naver?article_id=0004632890&amp;office_id=011&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1">‘37만전자’ 담는 ‘상위 1%’…1만피 향해 반도체·전력기기株 베팅[주식초고수는 지금]</a>
</dd>
<dd class="articleSummary">
										미래에셋증권에서 거래하는 고수익 투자자들이 19일 가장 많이 순매수한 종목은 삼성전자(005930), HD현대일렉트릭(267260), ..
										<span class="press">서울경제 </span>
<span class="bar">|</span>
<span class="wdate">2026-06-19 11:40:06</span>
</dd>
</dl>
</li>
<li class="block1">
<dl>
<dt class="thumb">
<a href="/news/news_read.naver?article_id=0016147980&amp;office_id=001&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1"><img onerror="this.src='https://ssl.pstatic.net/static/nfinance/2017/02/27/thumb_72x54.gif'" src="https://imgnews.pstatic.net/image/thumb70/001/2026/06/19/16147980.jpg"/></a>
</dt>
<dd class="articleSubject">
<a href="/news/news_read.naver?article_id=0016147980&amp;office_id=001&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1">코스피, 2%대↑ 9,200선 등락…코스닥은 1,000선 내줘</a>
</dd>
<dd class="articleSummary">
										국내증시 시총 첫 8천조…하이닉스 시총 2천조 돌파 코스닥 또 하락해 1,000 아래로 전날 '9천피'(9,000)를 돌파했던 코스피가..
										<span class="press">연합뉴스 </span>
<span class="bar">|</span>
<span class="wdate">2026-06-19 11:38:08</span>
</dd>
</dl>
</li>
<li class="block1">
<dl>
<dt class="thumb">
<a href="/news/news_read.naver?article_id=0005374355&amp;office_id=008&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1"><img onerror="this.src='https://ssl.pstatic.net/static/nfinance/2017/02/27/thumb_72x54.gif'" src="https://imgnews.pstatic.net/image/thumb70/008/2026/06/19/5374355.jpg"/></a>
</dt>
<dd class="articleSubject">
<a href="/news/news_read.naver?article_id=0005374355&amp;office_id=008&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1">'삼전닉스 패밀리' 일제히 신고가…코스피 최고치 행진 이끈다</a>
</dd>
<dd class="articleSummary">
										코스피가 9000선을 터치한 지 하루 만에 9300선까지 돌파했다. 반도체 대장주인 삼성전자와 SK하이닉스뿐 아니라 두 회사의 지분을 ..
										<span class="press">머니투데이 </span>
<span class="bar">|</span>
<span class="wdate">2026-06-19 11:37:05</span>
</dd>
</dl>
</li>
<li class="block1">
<dl>
<dt class="thumb">
<a href="/news/news_read.naver?article_id=0002658854&amp;office_id=016&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1"><img onerror="this.src='https://ssl.pstatic.net/static/nfinance/2017/02/27/thumb_72x54.gif'" src="https://imgnews.pstatic.net/image/thumb70/016/2026/06/19/2658854.jpg"/></a>
</dt>
<dd class="articleSubject">
<a href="/news/news_read.naver?article_id=0002658854&amp;office_id=016&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1">60대이상, 2배·3배 해외 ETF 대거 편입 [머니무브 뉴웨이브][H-EXCLUSIVE]</a>
</dd>
<dd class="articleSummary">
										코스피 지수가 9000선을 넘어선 강세장 속에서 60대 이상 투자자도 대거 2배·3배 레버리지 상장지수펀드(ETF) 상품에 투자하고 있..
										<span class="press">헤럴드경제 </span>
<span class="bar">|</span>
<span class="wdate">2026-06-19 11:19:15</span>
</dd>
</dl>
</li>
<li class="block1">
<dl>
<dt class="thumb">
<a href="/news/news_read.naver?article_id=0002658850&amp;office_id=016&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1"><img onerror="this.src='https://ssl.pstatic.net/static/nfinance/2017/02/27/thumb_72x54.gif'" src="https://imgnews.pstatic.net/image/thumb70/016/2026/06/19/2658850.jpg"/></a>
</dt>
<dd class="articleSubject">
<a href="/news/news_read.naver?article_id=0002658850&amp;office_id=016&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1">“전세금 빼서 주식에”…고위험 레버리지도 거침없는 6070 [머니무브 뉴웨이브]</a>
</dd>
<dd class="articleSummary">
										“전세 대신 월세를 살기로 했어요. 그 돈은 주식에 전부 넣었습니다.” 6월 초 서울 한 증권사 투자센터. 점심시간이 막 지난 시간이지..
										<span class="press">헤럴드경제 </span>
<span class="bar">|</span>
<span class="wdate">2026-06-19 11:18:10</span>
</dd>
</dl>
</li>
<li class="block1">
<dl>
<dt class="thumb">
<a href="/news/news_read.naver?article_id=0002658845&amp;office_id=016&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1"><img onerror="this.src='https://ssl.pstatic.net/static/nfinance/2017/02/27/thumb_72x54.gif'" src="https://imgnews.pstatic.net/image/thumb70/016/2026/06/19/2658845.jpg"/></a>
</dt>
<dd class="articleSubject">
<a href="/news/news_read.naver?article_id=0002658845&amp;office_id=016&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1">삼성·SK그룹주 첫 5000조 돌파…코스피 70% 차지</a>
</dd>
<dd class="articleSummary">
										코스피가 사상 처음으로 9000선을 돌파한 데에는 삼성전자와 SK하이닉스의 급등이 주효했다. 이에 힘입어 삼성그룹과 SK그룹 상장 계열..
										<span class="press">헤럴드경제 </span>
<span class="bar">|</span>
<span class="wdate">2026-06-19 11:17:07</span>
</dd>
</dl>
</li>
<li class="block1">
<dl>
<dt class="thumb">
<a href="/news/news_read.naver?article_id=0002658844&amp;office_id=016&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1"><img onerror="this.src='https://ssl.pstatic.net/static/nfinance/2017/02/27/thumb_72x54.gif'" src="https://imgnews.pstatic.net/image/thumb70/016/2026/06/19/2658844.jpg"/></a>
</dt>
<dd class="articleSubject">
<a href="/news/news_read.naver?article_id=0002658844&amp;office_id=016&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1">만스피 시대 목전…새로운 ‘M·A·P’ 열렸다</a>
</dd>
<dd class="articleSummary">
										코스피가 전인미답의 9000선 고지를 밟았다. 코스피 상장 기업들의 합산 시가총액은 사상 처음으로 7400조원을 돌파했다. 지난해 말과..
										<span class="press">헤럴드경제 </span>
<span class="bar">|</span>
<span class="wdate">2026-06-19 11:16:11</span>
</dd>
</dl>
</li>
<li class="block1">
<dl>
<dt class="thumb">
<a href="/news/news_read.naver?article_id=0002658812&amp;office_id=016&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1"><img onerror="this.src='https://ssl.pstatic.net/static/nfinance/2017/02/27/thumb_72x54.gif'" src="https://imgnews.pstatic.net/image/thumb70/016/2026/06/19/2658812.jpg"/></a>
</dt>
<dd class="articleSubject">
<a href="/news/news_read.naver?article_id=0002658812&amp;office_id=016&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1">SK하이닉스 이러다 삼성전자 추월?…7% 급등에 ‘280만닉스’, 시총 2000조 돌파 [종목 Pick]</a>
</dd>
<dd class="articleSummary">
										SK하이닉스가 19일 장 초반 7% 넘게 급등하며 사상 처음으로 ‘280만 닉스’에 도달했다. SK하이닉스의 시가총액은 2000조원을 ..
										<span class="press">헤럴드경제 </span>
<span class="bar">|</span>
<span class="wdate">2026-06-19 11:01:10</span>
</dd>
</dl>
</li>
<li class="block1">
<dl>
<dt class="thumb">
<a href="/news/news_read.naver?article_id=0005537170&amp;office_id=014&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1"><img onerror="this.src='https://ssl.pstatic.net/static/nfinance/2017/02/27/thumb_72x54.gif'" src="https://imgnews.pstatic.net/image/thumb70/014/2026/06/19/5537170.jpg"/></a>
</dt>
<dd class="articleSubject">
<a href="/news/news_read.naver?article_id=0005537170&amp;office_id=014&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1">"삼성전기 300만원 간다...MLCC·기판, 없어서 못 팔아"…KT&amp;G, 해외 매출 증가에 주주 환원 확대까지 '재평가' [株토피아]</a>
</dd>
<dd class="articleSummary">
										6월 19일 오전, 주요 증권사 리포트를 정리해드립니다. 삼성전기는 인공지능(AI) 서버용 적층세라믹콘덴서(MLCC)와 패키징 기판 모..
										<span class="press">파이낸셜뉴스 </span>
<span class="bar">|</span>
<span class="wdate">2026-06-19 11:00:11</span>
</dd>
</dl>
</li>
<li class="block1">
<dl>
<dt class="thumb">
<a href="/news/news_read.naver?article_id=0004632866&amp;office_id=011&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1"><img onerror="this.src='https://ssl.pstatic.net/static/nfinance/2017/02/27/thumb_72x54.gif'" src="https://imgnews.pstatic.net/image/thumb70/011/2026/06/19/4632866.jpg"/></a>
</dt>
<dd class="articleSubject">
<a href="/news/news_read.naver?article_id=0004632866&amp;office_id=011&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1">“너도 주식한다고 했지? 꽤 벌었겠네”…이 말에 코스닥 개미들은 ‘눈물’</a>
</dd>
<dd class="articleSummary">
										코스피가 사상 처음으로 9000선을 넘어섰지만 코스닥은 철저히 소외됐다. 연초 이후 두 지수의 수익률 격차는 100%포인트를 웃돌고 있..
										<span class="press">서울경제 </span>
<span class="bar">|</span>
<span class="wdate">2026-06-19 10:43:08</span>
</dd>
</dl>
</li>
<li class="block1">
<dl>
<dt class="thumb">
<a href="/news/news_read.naver?article_id=0004632860&amp;office_id=011&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1"><img onerror="this.src='https://ssl.pstatic.net/static/nfinance/2017/02/27/thumb_72x54.gif'" src="https://imgnews.pstatic.net/image/thumb70/011/2026/06/19/4632860.jpg"/></a>
</dt>
<dd class="articleSubject">
<a href="/news/news_read.naver?article_id=0004632860&amp;office_id=011&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1">스페이스X에 꽂힌 서학개미…사흘 만에 2.7조 쓸어담았다[코주부]</a>
</dd>
<dd class="articleSummary">
										미국 증시에 투자하는 국내 개인투자자들이 우주항공 기업 스페이스X로 빠르게 몰리고 있다. 상장 직후 주가가 급등하자 이른바 ‘서학개미’..
										<span class="press">서울경제 </span>
<span class="bar">|</span>
<span class="wdate">2026-06-19 10:36:14</span>
</dd>
</dl>
</li>
<li class="block1">
<dl>
<dt class="thumb">
<a href="/news/news_read.naver?article_id=0005537151&amp;office_id=014&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1"><img onerror="this.src='https://ssl.pstatic.net/static/nfinance/2017/02/27/thumb_72x54.gif'" src="https://imgnews.pstatic.net/image/thumb70/014/2026/06/19/5537151.jpg"/></a>
</dt>
<dd class="articleSubject">
<a href="/news/news_read.naver?article_id=0005537151&amp;office_id=014&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1">'삼전·닉스' 믿은 개인들 웃었다…8000→9000 구간 수익률 압승</a>
</dd>
<dd class="articleSummary">
										코스피가 종가 기준 8000선을 돌파한 이후 9000선을 넘어서는 과정에서 가장 큰 승자는 삼성전자와 SK하이닉스를 선택한 개인 투자자..
										<span class="press">파이낸셜뉴스 </span>
<span class="bar">|</span>
<span class="wdate">2026-06-19 10:15:11</span>
</dd>
</dl>
</li>
<li class="block1">
<dl>
<dt class="thumb">
<a href="/news/news_read.naver?article_id=0001255937&amp;office_id=215&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1"><img onerror="this.src='https://ssl.pstatic.net/static/nfinance/2017/02/27/thumb_72x54.gif'" src="https://imgnews.pstatic.net/image/thumb70/215/2026/06/19/1255937.jpg"/></a>
</dt>
<dd class="articleSubject">
<a href="/news/news_read.naver?article_id=0001255937&amp;office_id=215&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1">형님 뛰자 동반 '뜀박질'…목표주가 38만→62만원 "우리는 더 오른다"</a>
</dd>
<dd class="articleSummary">
										코스피가 19일 장 초반 9,300선을 돌파하며 다시 사상 최고치를 경신했다. 미국발 반도체 호재에 힘입어 삼성전자와 SK하이닉스가 나..
										<span class="press">한국경제TV </span>
<span class="bar">|</span>
<span class="wdate">2026-06-19 10:12:38</span>
</dd>
</dl>
</li>
<li class="block1">
<dl>
<dt class="thumb">
<a href="/news/news_read.naver?article_id=0004632843&amp;office_id=011&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1"><img onerror="this.src='https://ssl.pstatic.net/static/nfinance/2017/02/27/thumb_72x54.gif'" src="https://imgnews.pstatic.net/image/thumb70/011/2026/06/19/4632843.jpg"/></a>
</dt>
<dd class="articleSubject">
<a href="/news/news_read.naver?article_id=0004632843&amp;office_id=011&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1">SK스퀘어, 189만 원 ‘터치’…목표가 뚫고 9%대 ‘급등’[이런국장 저런주식]</a>
</dd>
<dd class="articleSummary">
										SK스퀘어(402340)가 19일 장 초반 9% 넘게 급등하며 장중 신고가를 다시 썼다. 핵심 자회사인 SK하이닉스(000660) 주가..
										<span class="press">서울경제 </span>
<span class="bar">|</span>
<span class="wdate">2026-06-19 10:07:15</span>
</dd>
</dl>
</li>
<li class="block1">
<dl>
<dt class="thumb">
<a href="/news/news_read.naver?article_id=0004632840&amp;office_id=011&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1"><img onerror="this.src='https://ssl.pstatic.net/static/nfinance/2017/02/27/thumb_72x54.gif'" src="https://imgnews.pstatic.net/image/thumb70/011/2026/06/19/4632840.jpg"/></a>
</dt>
<dd class="articleSubject">
<a href="/news/news_read.naver?article_id=0004632840&amp;office_id=011&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1">매파 연준 쇼크…환율 1527원 다시 뚫었다</a>
</dd>
<dd class="articleSummary">
										▲ AI 프리즘* 맞춤형 경제 브리핑 * 편집자 주: ‘AI PRISM’(Personalized Report &amp; Insight Summ..
										<span class="press">서울경제 </span>
<span class="bar">|</span>
<span class="wdate">2026-06-19 10:06:11</span>
</dd>
</dl>
</li>
<li class="block1">
<dl>
<dt class="thumb">
<a href="/news/news_read.naver?article_id=0006309682&amp;office_id=018&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1"><img onerror="this.src='https://ssl.pstatic.net/static/nfinance/2017/02/27/thumb_72x54.gif'" src="https://imgnews.pstatic.net/image/thumb70/018/2026/06/19/6309682.jpg"/></a>
</dt>
<dd class="articleSubject">
<a href="/news/news_read.naver?article_id=0006309682&amp;office_id=018&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1">FTSE 리밸런싱에 쏠린 눈…“SK하이닉스 장마감 매도 유의”</a>
</dd>
<dd class="articleSummary">
										FTSE Korea 리밸런싱을 앞두고 삼성전자(005930)와 SK하이닉스(000660)의 비중 조정에 따른 장마감 수급 변동성에 유의..
										<span class="press">이데일리 </span>
<span class="bar">|</span>
<span class="wdate">2026-06-19 10:04:09</span>
</dd>
</dl>
</li>
<li class="block1">
<dl>
<dt class="thumb">
<a href="/news/news_read.naver?article_id=0004632828&amp;office_id=011&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1"><img onerror="this.src='https://ssl.pstatic.net/static/nfinance/2017/02/27/thumb_72x54.gif'" src="https://imgnews.pstatic.net/image/thumb70/011/2026/06/19/4632828.jpg"/></a>
</dt>
<dd class="articleSubject">
<a href="/news/news_read.naver?article_id=0004632828&amp;office_id=011&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1">“전력기기株 다시 전류 통했나”…LS일렉 12%·효성重 8% 급등[이런국장 저런주식]</a>
</dd>
<dd class="articleSummary">
										전력기기주가 19일 장중 일제히 강세를 보이고 있다. 인공지능(AI) 데이터센터 확대에 따른 전력망 투자 기대가 이어지는 가운데 최근 ..
										<span class="press">서울경제 </span>
<span class="bar">|</span>
<span class="wdate">2026-06-19 09:50:07</span>
</dd>
</dl>
</li>
<li class="block1">
<dl>
<dt class="thumb">
<a href="/news/news_read.naver?article_id=0002658737&amp;office_id=016&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1"><img onerror="this.src='https://ssl.pstatic.net/static/nfinance/2017/02/27/thumb_72x54.gif'" src="https://imgnews.pstatic.net/image/thumb70/016/2026/06/19/2658737.jpg"/></a>
</dt>
<dd class="articleSubject">
<a href="/news/news_read.naver?article_id=0002658737&amp;office_id=016&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1">무섭게 오르는 코스피…구천피 넘자마자 9300 돌파 ‘또 최고치’ [투자360]</a>
</dd>
<dd class="articleSummary">
										전날 사상 처음으로 9000선 고지를 밟은 코스피가 19일 상승세를 이어가며 장중 최고치를 경신, 9300선마저 돌파했다. ‘팔천피’(..
										<span class="press">헤럴드경제 </span>
<span class="bar">|</span>
<span class="wdate">2026-06-19 09:40:07</span>
</dd>
</dl>
</li>
<li class="block1">
<dl>
<dt class="thumb">
<a href="/news/news_read.naver?article_id=0004632817&amp;office_id=011&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1"><img onerror="this.src='https://ssl.pstatic.net/static/nfinance/2017/02/27/thumb_72x54.gif'" src="https://imgnews.pstatic.net/image/thumb70/011/2026/06/19/4632817.jpg"/></a>
</dt>
<dd class="articleSubject">
<a href="/news/news_read.naver?article_id=0004632817&amp;office_id=011&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1">SK하이닉스 신고가에 시총 ‘2000조’↑…코스피 개장 직후 9300선 돌파[마켓시그널]</a>
</dd>
<dd class="articleSummary">
										코스피지수가 19일 장 초반 9300선을 돌파했다. 미국 증시에서 반도체주가 강세를 보인 데다 국내 증시에서도 삼성전자(005930)와..
										<span class="press">서울경제 </span>
<span class="bar">|</span>
<span class="wdate">2026-06-19 09:32:16</span>
</dd>
</dl>
</li>
<li class="block1">
<dl>
<dt class="thumb">
<a href="/news/news_read.naver?article_id=0005374269&amp;office_id=008&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1"><img onerror="this.src='https://ssl.pstatic.net/static/nfinance/2017/02/27/thumb_72x54.gif'" src="https://imgnews.pstatic.net/image/thumb70/008/2026/06/19/5374269.jpg"/></a>
</dt>
<dd class="articleSubject">
<a href="/news/news_read.naver?article_id=0005374269&amp;office_id=008&amp;mode=mainnews&amp;type=&amp;date=2026-06-19&amp;page=1">"오늘도 개미 열일" 9300피 뚫고 최고치…'반도체 훈풍' 삼전닉스 신고가</a>
</dd>
<dd class="articleSummary">
										코스피가 장 중 9300선을 돌파하며, 연일 사상 최고치 행진을 이어가고 있다. 미국과 이란의 종전 합의와 간밤 미국 증시 내 반도체주..
										<span class="press">머니투데이 </span>
<span class="bar">|</span>
<span class="wdate">2026-06-19 09:30:18</span>
</dd>
</dl>
</li>

### 마지막 페이지 체크 코드

In [38]:
import time

base_url = 'https://finance.naver.com/news/mainnews.naver'
article_list = []

page_num = 1
while True:
    news_url = f'{base_url}?&page={page_num}'
    response = requests.get(news_url)
    status_code = response.status_code
    if status_code == 200:
        html = response.text
        soup = BeautifulSoup(html, 'html.parser')
        articles = soup.select('.block1')

        for article in articles:
            title = article.select_one('.articleSubject > a').text.strip()
            link = article.select_one('.articleSubject > a').attrs['href']
            content = article.select_one('.articleSummary').contents[0].strip()
            press = article.select_one('.press').text.strip()
            date = article.select_one('.wdate').text.strip()
            
            article_list.append([title, link, content, press, date])

        print(f'{page_num}번째 페이지 - 기사 개수 {len(articles)}')

        # pgRP
        last_page_marker = soup.select_one('.pgRR')
        if last_page_marker is None:
            break

    else:
        print('요청 실패. 상태 코드:', status_code)
        break

    page_num += 1    
    time.sleep(5)

print(f'전체 기사 개수 {len(article_list)}')

1번째 페이지 - 기사 개수 20
2번째 페이지 - 기사 개수 20
3번째 페이지 - 기사 개수 20
4번째 페이지 - 기사 개수 20
5번째 페이지 - 기사 개수 5
전체 기사 개수 85

In [39]:
!python -m pip install pandas

Collecting pandas
  Using cached pandas-3.0.3-cp314-cp314-win_amd64.whl.metadata (19 kB)
Collecting numpy>=2.3.3 (from pandas)
  Using cached numpy-2.4.6-cp314-cp314-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in .\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Using cached tzdata-2026.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in .\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-3.0.3-cp314-cp314-win_amd64.whl (9.9 MB)
Using cached numpy-2.4.6-cp314-cp314-win_amd64.whl (12.5 MB)
Using cached tzdata-2026.2-py2.py3-none-any.whl (349 kB)
Installing collected packages: tzdata, numpy, pandas

   ---------------------------------------- 0/3 [tzdata]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   ---------------------------------------- 3/3 [pandas]

Successfully installed numpy-2.4.6 pandas-3.0.3 tzdata-2026.2

In [42]:
!python -m pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

In [44]:
import pandas as pd

df = pd.DataFrame(article_list, columns=['제목', 'URL', '요약', '언론사', '날짜'])
df.head()

,제목,URL,요약,언론사,날짜
0,MSCI 훈풍에 반도체 랠리…코스피 9500선 넘본다,/news/news_read.naver?article_id=0000099360&of...,미국 연방준비제도(Fed)의 통화정책 불확실성이 여전한 가운데 다음 주 국내 증시는...,이코노미스트,2026-06-19 15:07:07
1,"""반도체로 벌어 명품 산다""…백화점株, 지수상승률 '압도'",/news/news_read.naver?article_id=0001255972&of...,반도체 랠리가 연일 이어지는 가운데 호황의 온기가 뜻밖에도 백화점으로 흘러들고 있습...,한국경제TV,2026-06-19 14:51:15
2,삼성전기 마저 막혔다...불장 속 '빚투 브레이크' 걸린 개미,/news/news_read.naver?article_id=0001255968&of...,"코스피 9,000선 돌파와 함께 개인 투자자들의 이른바 '빚투'가 재차 과열될 조짐...",한국경제TV,2026-06-19 14:44:37
3,“스페이스X 상장? 두 배로 먹자”…레버리지 1083억원 사들인 ‘불개미’,/news/news_read.naver?article_id=0001172980&of...,스페이스X 2조원 사들인 서학개미 레버리지 ETF도 1038억원 순매수 “본주는 장...,조선비즈,2026-06-19 14:44:09
4,삼전과 120조 차이…2천조 넘은 하이닉스 '7월 분수령' [마켓딥다이브],/news/news_read.naver?article_id=0001255967&of...,"＜앵커＞ SK하이닉스 시가총액이 장중 2,000조 원을 넘어섰는데요. 중동 리스크로...",한국경제TV,2026-06-19 14:41:10

In [ ]:
# Excel 파일로 저장
df.to_excel('../data/finance_news.xlsx', index=False)

In [ ]:
# Excel 파일 읽기
df2 = pd.read_excel('../data/finance_news.xlsx')
df2.head()

,제목,URL,요약,언론사,날짜
0,MSCI 훈풍에 반도체 랠리…코스피 9500선 넘본다,/news/news_read.naver?article_id=0000099360&of...,미국 연방준비제도(Fed)의 통화정책 불확실성이 여전한 가운데 다음 주 국내 증시는...,이코노미스트,2026-06-19 15:07:07
1,"""반도체로 벌어 명품 산다""…백화점株, 지수상승률 '압도'",/news/news_read.naver?article_id=0001255972&of...,반도체 랠리가 연일 이어지는 가운데 호황의 온기가 뜻밖에도 백화점으로 흘러들고 있습...,한국경제TV,2026-06-19 14:51:15
2,삼성전기 마저 막혔다...불장 속 '빚투 브레이크' 걸린 개미,/news/news_read.naver?article_id=0001255968&of...,"코스피 9,000선 돌파와 함께 개인 투자자들의 이른바 '빚투'가 재차 과열될 조짐...",한국경제TV,2026-06-19 14:44:37
3,“스페이스X 상장? 두 배로 먹자”…레버리지 1083억원 사들인 ‘불개미’,/news/news_read.naver?article_id=0001172980&of...,스페이스X 2조원 사들인 서학개미 레버리지 ETF도 1038억원 순매수 “본주는 장...,조선비즈,2026-06-19 14:44:09
4,삼전과 120조 차이…2천조 넘은 하이닉스 '7월 분수령' [마켓딥다이브],/news/news_read.naver?article_id=0001255967&of...,"＜앵커＞ SK하이닉스 시가총액이 장중 2,000조 원을 넘어섰는데요. 중동 리스크로...",한국경제TV,2026-06-19 14:41:10